# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)



DESCRIPTOR = descriptor.FileDescriptor(
  name='devicestatus.proto',
  package='',
  serialized_pb='\n\x12\x64\x65vicestatus.proto\"\x1f\n\x0c\x64\x65vicestatus\x12\x0f\n\x07version\x18\x01 \x02(\r\"\xe9\x01\n\x14\x64\x65vicestatusresponse\x12\x0f\n\x07version\x18\x01 \x02(\r\x12-\n\x07\x64rivers\x18\x02 \x03(\x0b\x32\x1c.devicestatusresponse.driver\x1a:\n\x06\x64\x65vice\x12\x0f\n\x07version\x18\x01 \x02(\r\x12\x0c\n\x04\x62\x64id\x18\x02 \x01(\t\x12\x11\n\ttuner_ids\x18\x03 \x03(\t\x1aU\n\x06\x64river\x12\x0f\n\x07version\x18\x01 \x02(\r\x12\x0b\n\x03\x64\x63n\x18\x02 \x01(\t\x12-\n\x07\x64\x65vices\x18\x03 \x03(\x0b\x32\x1c.devicestatusresponse.device')




_DEVICESTATUS = descriptor.Descriptor(
  name='devicestatus',
  full_name='devicestatus',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='version', full_name='devicestatus.version', index=0,
      number=1, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=22,
  serialized_end=53,
)


_DEVICESTATUSRESPONSE_DEVICE = descriptor.Descriptor(
  name='device',
  full_name='devicestatusresponse.device',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='version', full_name='devicestatusresponse.device.version', index=0,
      number=1, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='bdid', full_name='devicestatusresponse.device.bdid', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='tuner_ids', full_name='devicestatusresponse.device.tuner_ids', index=2,
      number=3, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=144,
  serialized_end=202,
)

_DEVICESTATUSRESPONSE_DRIVER = descriptor.Descriptor(
  name='driver',
  full_name='devicestatusresponse.driver',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='version', full_name='devicestatusresponse.driver.version', index=0,
      number=1, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='dcn', full_name='devicestatusresponse.driver.dcn', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='devices', full_name='devicestatusresponse.driver.devices', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=204,
  serialized_end=289,
)

_DEVICESTATUSRESPONSE = descriptor.Descriptor(
  name='devicestatusresponse',
  full_name='devicestatusresponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='version', full_name='devicestatusresponse.version', index=0,
      number=1, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='drivers', full_name='devicestatusresponse.drivers', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_DEVICESTATUSRESPONSE_DEVICE, _DEVICESTATUSRESPONSE_DRIVER, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=56,
  serialized_end=289,
)

_DEVICESTATUSRESPONSE_DEVICE.containing_type = _DEVICESTATUSRESPONSE;
_DEVICESTATUSRESPONSE_DRIVER.fields_by_name['devices'].message_type = _DEVICESTATUSRESPONSE_DEVICE
_DEVICESTATUSRESPONSE_DRIVER.containing_type = _DEVICESTATUSRESPONSE;
_DEVICESTATUSRESPONSE.fields_by_name['drivers'].message_type = _DEVICESTATUSRESPONSE_DRIVER
DESCRIPTOR.message_types_by_name['devicestatus'] = _DEVICESTATUS
DESCRIPTOR.message_types_by_name['devicestatusresponse'] = _DEVICESTATUSRESPONSE

class devicestatus(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _DEVICESTATUS
  
  # @@protoc_insertion_point(class_scope:devicestatus)

class devicestatusresponse(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  
  class device(message.Message):
    __metaclass__ = reflection.GeneratedProtocolMessageType
    DESCRIPTOR = _DEVICESTATUSRESPONSE_DEVICE
    
    # @@protoc_insertion_point(class_scope:devicestatusresponse.device)
  
  class driver(message.Message):
    __metaclass__ = reflection.GeneratedProtocolMessageType
    DESCRIPTOR = _DEVICESTATUSRESPONSE_DRIVER
    
    # @@protoc_insertion_point(class_scope:devicestatusresponse.driver)
  DESCRIPTOR = _DEVICESTATUSRESPONSE
  
  # @@protoc_insertion_point(class_scope:devicestatusresponse)

# @@protoc_insertion_point(module_scope)
