# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)



DESCRIPTOR = descriptor.FileDescriptor(
  name='device_list.proto',
  package='tvserver',
  serialized_pb='\n\x11\x64\x65vice_list.proto\x12\x08tvserver\"+\n\x0b\x64\x65vice_list\x12\x0f\n\x07version\x18\x01 \x02(\r\x12\x0b\n\x03\x64\x63n\x18\x02 \x01(\t\"\xaf\x01\n\x13\x64\x65vice_listresponse\x12\x0f\n\x07version\x18\x01 \x02(\r\x12\x0f\n\x07success\x18\x02 \x01(\x08\x12\x35\n\x07\x64\x65vices\x18\x03 \x03(\x0b\x32$.tvserver.device_listresponse.device\x1a?\n\x06\x64\x65vice\x12\x0c\n\x04\x62\x64id\x18\x01 \x01(\t\x12\x0f\n\x07\x61\x64\x64ress\x18\x02 \x01(\t\x12\x16\n\x0etuner_quantity\x18\x03 \x01(\r')




_DEVICE_LIST = descriptor.Descriptor(
  name='device_list',
  full_name='tvserver.device_list',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='version', full_name='tvserver.device_list.version', index=0,
      number=1, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='dcn', full_name='tvserver.device_list.dcn', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=31,
  serialized_end=74,
)


_DEVICE_LISTRESPONSE_DEVICE = descriptor.Descriptor(
  name='device',
  full_name='tvserver.device_listresponse.device',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='bdid', full_name='tvserver.device_listresponse.device.bdid', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='address', full_name='tvserver.device_listresponse.device.address', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='tuner_quantity', full_name='tvserver.device_listresponse.device.tuner_quantity', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=189,
  serialized_end=252,
)

_DEVICE_LISTRESPONSE = descriptor.Descriptor(
  name='device_listresponse',
  full_name='tvserver.device_listresponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='version', full_name='tvserver.device_listresponse.version', index=0,
      number=1, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='success', full_name='tvserver.device_listresponse.success', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='devices', full_name='tvserver.device_listresponse.devices', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_DEVICE_LISTRESPONSE_DEVICE, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=77,
  serialized_end=252,
)

_DEVICE_LISTRESPONSE_DEVICE.containing_type = _DEVICE_LISTRESPONSE;
_DEVICE_LISTRESPONSE.fields_by_name['devices'].message_type = _DEVICE_LISTRESPONSE_DEVICE
DESCRIPTOR.message_types_by_name['device_list'] = _DEVICE_LIST
DESCRIPTOR.message_types_by_name['device_listresponse'] = _DEVICE_LISTRESPONSE

class device_list(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _DEVICE_LIST
  
  # @@protoc_insertion_point(class_scope:tvserver.device_list)

class device_listresponse(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  
  class device(message.Message):
    __metaclass__ = reflection.GeneratedProtocolMessageType
    DESCRIPTOR = _DEVICE_LISTRESPONSE_DEVICE
    
    # @@protoc_insertion_point(class_scope:tvserver.device_listresponse.device)
  DESCRIPTOR = _DEVICE_LISTRESPONSE
  
  # @@protoc_insertion_point(class_scope:tvserver.device_listresponse)

# @@protoc_insertion_point(module_scope)
