# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)



DESCRIPTOR = descriptor.FileDescriptor(
  name='devicelist.proto',
  package='',
  serialized_pb='\n\x10\x64\x65vicelist.proto\"*\n\ndevicelist\x12\x0f\n\x07version\x18\x01 \x02(\r\x12\x0b\n\x03\x64\x63n\x18\x02 \x01(\t\"\xa4\x01\n\x12\x64\x65vicelistresponse\x12\x0f\n\x07version\x18\x01 \x02(\r\x12\x0f\n\x07success\x18\x02 \x01(\x08\x12+\n\x07\x64\x65vices\x18\x03 \x03(\x0b\x32\x1a.devicelistresponse.device\x1a?\n\x06\x64\x65vice\x12\x0c\n\x04\x62\x64id\x18\x01 \x01(\t\x12\x0f\n\x07\x61\x64\x64ress\x18\x02 \x01(\t\x12\x16\n\x0etuner_quantity\x18\x03 \x01(\r')




_DEVICELIST = descriptor.Descriptor(
  name='devicelist',
  full_name='devicelist',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='version', full_name='devicelist.version', index=0,
      number=1, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='dcn', full_name='devicelist.dcn', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=20,
  serialized_end=62,
)


_DEVICELISTRESPONSE_DEVICE = descriptor.Descriptor(
  name='device',
  full_name='devicelistresponse.device',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='bdid', full_name='devicelistresponse.device.bdid', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='address', full_name='devicelistresponse.device.address', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='tuner_quantity', full_name='devicelistresponse.device.tuner_quantity', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=166,
  serialized_end=229,
)

_DEVICELISTRESPONSE = descriptor.Descriptor(
  name='devicelistresponse',
  full_name='devicelistresponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='version', full_name='devicelistresponse.version', index=0,
      number=1, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='success', full_name='devicelistresponse.success', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='devices', full_name='devicelistresponse.devices', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_DEVICELISTRESPONSE_DEVICE, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=65,
  serialized_end=229,
)

_DEVICELISTRESPONSE_DEVICE.containing_type = _DEVICELISTRESPONSE;
_DEVICELISTRESPONSE.fields_by_name['devices'].message_type = _DEVICELISTRESPONSE_DEVICE
DESCRIPTOR.message_types_by_name['devicelist'] = _DEVICELIST
DESCRIPTOR.message_types_by_name['devicelistresponse'] = _DEVICELISTRESPONSE

class devicelist(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _DEVICELIST
  
  # @@protoc_insertion_point(class_scope:devicelist)

class devicelistresponse(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  
  class device(message.Message):
    __metaclass__ = reflection.GeneratedProtocolMessageType
    DESCRIPTOR = _DEVICELISTRESPONSE_DEVICE
    
    # @@protoc_insertion_point(class_scope:devicelistresponse.device)
  DESCRIPTOR = _DEVICELISTRESPONSE
  
  # @@protoc_insertion_point(class_scope:devicelistresponse)

# @@protoc_insertion_point(module_scope)
