# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)



DESCRIPTOR = descriptor.FileDescriptor(
  name='driverlist.proto',
  package='',
  serialized_pb='\n\x10\x64riverlist.proto\"\x1d\n\ndriverlist\x12\x0f\n\x07version\x18\x01 \x02(\r\"\x9d\x01\n\x12\x64riverlistresponse\x12\x0f\n\x07version\x18\x01 \x02(\r\x12\x0f\n\x07success\x18\x02 \x01(\x08\x12+\n\x07\x64rivers\x18\x03 \x03(\x0b\x32\x1a.driverlistresponse.driver\x1a\x38\n\x06\x64river\x12\x0b\n\x03\x64\x63n\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x03 \x01(\t')




_DRIVERLIST = descriptor.Descriptor(
  name='driverlist',
  full_name='driverlist',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='version', full_name='driverlist.version', index=0,
      number=1, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=20,
  serialized_end=49,
)


_DRIVERLISTRESPONSE_DRIVER = descriptor.Descriptor(
  name='driver',
  full_name='driverlistresponse.driver',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='dcn', full_name='driverlistresponse.driver.dcn', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='name', full_name='driverlistresponse.driver.name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='description', full_name='driverlistresponse.driver.description', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=153,
  serialized_end=209,
)

_DRIVERLISTRESPONSE = descriptor.Descriptor(
  name='driverlistresponse',
  full_name='driverlistresponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='version', full_name='driverlistresponse.version', index=0,
      number=1, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='success', full_name='driverlistresponse.success', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='drivers', full_name='driverlistresponse.drivers', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_DRIVERLISTRESPONSE_DRIVER, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=52,
  serialized_end=209,
)

_DRIVERLISTRESPONSE_DRIVER.containing_type = _DRIVERLISTRESPONSE;
_DRIVERLISTRESPONSE.fields_by_name['drivers'].message_type = _DRIVERLISTRESPONSE_DRIVER
DESCRIPTOR.message_types_by_name['driverlist'] = _DRIVERLIST
DESCRIPTOR.message_types_by_name['driverlistresponse'] = _DRIVERLISTRESPONSE

class driverlist(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _DRIVERLIST
  
  # @@protoc_insertion_point(class_scope:driverlist)

class driverlistresponse(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  
  class driver(message.Message):
    __metaclass__ = reflection.GeneratedProtocolMessageType
    DESCRIPTOR = _DRIVERLISTRESPONSE_DRIVER
    
    # @@protoc_insertion_point(class_scope:driverlistresponse.driver)
  DESCRIPTOR = _DRIVERLISTRESPONSE
  
  # @@protoc_insertion_point(class_scope:driverlistresponse)

# @@protoc_insertion_point(module_scope)
