# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)



DESCRIPTOR = descriptor.FileDescriptor(
  name='tune.proto',
  package='tvserver',
  serialized_pb='\n\ntune.proto\x12\x08tvserver\"\x84\x04\n\x04tune\x12\x0f\n\x07version\x18\x01 \x02(\r\x12\x14\n\x0ctuning_bigid\x18\x02 \x01(\t\x12\x37\n\x0eparameter_type\x18\x03 \x01(\x0e\x32\x1f.tvserver.tune.parameter_type_e\x12+\n\x08vchannel\x18\x04 \x01(\x0b\x32\x19.tvserver.tune.vchannel_m\x12\x42\n\x13\x63hannelsconf_record\x18\x05 \x01(\x0b\x32%.tvserver.tune.channels_conf_record_m\x12\'\n\x06target\x18\x06 \x01(\x0b\x32\x17.tvserver.tune.target_m\x1a\x1e\n\nvchannel_m\x12\x10\n\x08vchannel\x18\x01 \x01(\r\x1a\x85\x01\n\x16\x63hannels_conf_record_m\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x11\n\tfrequency\x18\x02 \x01(\r\x12\x12\n\nmodulation\x18\x03 \x01(\t\x12\x10\n\x08video_id\x18\x04 \x01(\r\x12\x10\n\x08\x61udio_id\x18\x05 \x01(\r\x12\x12\n\nprogram_id\x18\x06 \x01(\r\x1a&\n\x08target_m\x12\x0c\n\x04host\x18\x01 \x01(\t\x12\x0c\n\x04port\x18\x02 \x01(\x05\"2\n\x10parameter_type_e\x12\x0c\n\x08VCHANNEL\x10\x00\x12\x10\n\x0c\x43HANNELSCONF\x10\x01')



_TUNE_PARAMETER_TYPE_E = descriptor.EnumDescriptor(
  name='parameter_type_e',
  full_name='tvserver.tune.parameter_type_e',
  filename=None,
  file=DESCRIPTOR,
  values=[
    descriptor.EnumValueDescriptor(
      name='VCHANNEL', index=0, number=0,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='CHANNELSCONF', index=1, number=1,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=491,
  serialized_end=541,
)


_TUNE_VCHANNEL_M = descriptor.Descriptor(
  name='vchannel_m',
  full_name='tvserver.tune.vchannel_m',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='vchannel', full_name='tvserver.tune.vchannel_m.vchannel', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=283,
  serialized_end=313,
)

_TUNE_CHANNELS_CONF_RECORD_M = descriptor.Descriptor(
  name='channels_conf_record_m',
  full_name='tvserver.tune.channels_conf_record_m',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='name', full_name='tvserver.tune.channels_conf_record_m.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='frequency', full_name='tvserver.tune.channels_conf_record_m.frequency', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='modulation', full_name='tvserver.tune.channels_conf_record_m.modulation', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='video_id', full_name='tvserver.tune.channels_conf_record_m.video_id', index=3,
      number=4, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='audio_id', full_name='tvserver.tune.channels_conf_record_m.audio_id', index=4,
      number=5, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='program_id', full_name='tvserver.tune.channels_conf_record_m.program_id', index=5,
      number=6, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=316,
  serialized_end=449,
)

_TUNE_TARGET_M = descriptor.Descriptor(
  name='target_m',
  full_name='tvserver.tune.target_m',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='host', full_name='tvserver.tune.target_m.host', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='port', full_name='tvserver.tune.target_m.port', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=451,
  serialized_end=489,
)

_TUNE = descriptor.Descriptor(
  name='tune',
  full_name='tvserver.tune',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='version', full_name='tvserver.tune.version', index=0,
      number=1, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='tuning_bigid', full_name='tvserver.tune.tuning_bigid', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='parameter_type', full_name='tvserver.tune.parameter_type', index=2,
      number=3, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='vchannel', full_name='tvserver.tune.vchannel', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='channelsconf_record', full_name='tvserver.tune.channelsconf_record', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='target', full_name='tvserver.tune.target', index=5,
      number=6, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_TUNE_VCHANNEL_M, _TUNE_CHANNELS_CONF_RECORD_M, _TUNE_TARGET_M, ],
  enum_types=[
    _TUNE_PARAMETER_TYPE_E,
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=25,
  serialized_end=541,
)

_TUNE_VCHANNEL_M.containing_type = _TUNE;
_TUNE_CHANNELS_CONF_RECORD_M.containing_type = _TUNE;
_TUNE_TARGET_M.containing_type = _TUNE;
_TUNE.fields_by_name['parameter_type'].enum_type = _TUNE_PARAMETER_TYPE_E
_TUNE.fields_by_name['vchannel'].message_type = _TUNE_VCHANNEL_M
_TUNE.fields_by_name['channelsconf_record'].message_type = _TUNE_CHANNELS_CONF_RECORD_M
_TUNE.fields_by_name['target'].message_type = _TUNE_TARGET_M
_TUNE_PARAMETER_TYPE_E.containing_type = _TUNE;
DESCRIPTOR.message_types_by_name['tune'] = _TUNE

class tune(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  
  class vchannel_m(message.Message):
    __metaclass__ = reflection.GeneratedProtocolMessageType
    DESCRIPTOR = _TUNE_VCHANNEL_M
    
    # @@protoc_insertion_point(class_scope:tvserver.tune.vchannel_m)
  
  class channels_conf_record_m(message.Message):
    __metaclass__ = reflection.GeneratedProtocolMessageType
    DESCRIPTOR = _TUNE_CHANNELS_CONF_RECORD_M
    
    # @@protoc_insertion_point(class_scope:tvserver.tune.channels_conf_record_m)
  
  class target_m(message.Message):
    __metaclass__ = reflection.GeneratedProtocolMessageType
    DESCRIPTOR = _TUNE_TARGET_M
    
    # @@protoc_insertion_point(class_scope:tvserver.tune.target_m)
  DESCRIPTOR = _TUNE
  
  # @@protoc_insertion_point(class_scope:tvserver.tune)

# @@protoc_insertion_point(module_scope)
